-- TaskFlow reliable job dispatch outbox. Run after schema.sql and jobs-schema.sql.
-- Safe to rerun; existing jobs remain unchanged and are not backfilled here.
CREATE TABLE IF NOT EXISTS outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id UUID NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    event_type VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    attempts INTEGER NOT NULL DEFAULT 0,
    failures INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMPTZ,
    last_error TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_outbox_status CHECK (status IN ('pending', 'processing', 'failed', 'processed')),
    CONSTRAINT chk_outbox_attempts CHECK (attempts >= 0),
    CONSTRAINT chk_outbox_failures CHECK (failures >= 0),
    CONSTRAINT uq_outbox_job_event UNIQUE (job_id, event_type)
);

CREATE INDEX IF NOT EXISTS idx_outbox_dispatchable
    ON outbox_events (available_at, created_at, id)
    WHERE status IN ('pending', 'failed');
CREATE INDEX IF NOT EXISTS idx_outbox_stale_claims
    ON outbox_events (updated_at, id)
    WHERE status = 'processing';

-- Reconcile existing queued/delayed database jobs created before the dispatcher existed.
-- BullMQ job IDs are the PostgreSQL UUIDs, so already-enqueued jobs remain deduplicated.
INSERT INTO outbox_events (job_id, event_type)
SELECT id, 'job.dispatch' FROM jobs WHERE status IN ('waiting', 'delayed')
ON CONFLICT (job_id, event_type) DO NOTHING;
